os: osx
language: node_js
cache:
 - node_modules
node_js:
  - lts/*
addons:
  chrome: stable
  firefox: latest

branches:
  only:
    - gh-pages

script:
  - npm test

matrix:
  include:
  - name: "Chrome Stable"
    env: BROWSER=chrome
    addons:
      chrome: stable
  - name: "Firefox Stable"
    env: BROWSER=firefox
    addons:
      firefox: latest

notifications:
  email:
    recipients:
      forward-webrtc-github@webrtc.org
    on_success: change
    on_failure: always
