os: osx
language: node_js
cache:
 - node_modules
node_js:
  - lts/*

before_install:
  - sudo safaridriver --enable
before_script:
  - defaults write com.apple.Safari IncludeDevelopMenu YES
  - defaults write com.apple.Safari AllowRemoteAutomation 1
  - defaults write com.apple.Safari WebKit2ICECandidateFilteringEnabled 0
  - defaults write com.apple.Safari WebKit2MockCaptureDevicesEnabled 1
  - defaults write com.apple.Safari WebKit2MediaCaptureRequiresSecureConnection 0

branches:
  only:
    - gh-pages

script:
  - npm test

matrix:
  include:
  - name: "Chrome Stable"
    env: BROWSER=chrome
    addons:
      chrome: stable
  - name: "Chrome Beta"
    env: BROWSER=chrome
    addons:
      chrome: beta
  - name: "Safari"
    env: BROWSER=safari
#  - name: "Firefox ESR"
#    env: BROWSER=firefox
#    addons:
#      firefox: latest-esr
#  - name: "Firefox Stable"
#    env: BROWSER=firefox
#    addons:
#      firefox: latest
#  - name: "Firefox Beta"
#    env: BROWSER=firefox
#    addons:
#      firefox: latest-beta

notifications:
  email:
    recipients:
      forward-webrtc-github@webrtc.org
    on_success: change
    on_failure: always
