os: osx
language: node_js
cache:
 - node_modules
node_js:
  - lts/*
addons:
  chrome: stable
  firefox: latest

branches:
  only:
    - gh-pages

script:
  - npm test

env:
  matrix:
  - BROWSER=chrome
#  - BROWSER=firefox
#  - BROWSER=safari

notifications:
  email:
    recipients:
      forward-webrtc-github@webrtc.org
    on_success: change
    on_failure: always
